/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chessproject2.GUI;


import chessproject2.ChessDB.BoardStateCodec;
import chessproject2.ChessDB.SaveGameDB;
import java.awt.Color;
import chessproject2.GUI.PawnPromotionPanel.PromotionSelectionListener;
import chessproject2.Check;
import chessproject2.ChessDB.PlayerDB;
import chessproject2.Pieces.Piece;


/**
 *
 * @author RyanL
 */
public class GameFrame extends javax.swing.JFrame implements PawnPromotionPanel.PromotionSelectionListener {

    private String whitePlayerName;
    private String blackPlayerName;
    // Add fields to temporarily store the promotion square
    private int promotionRow = -1;
    private int promotionCol = -1;

    public GameFrame()
    {
        this(Check.gameName, Check.whiteName, Check.blackName);
        boardPanel.loadState(BoardPanel.board, Check.turn);
        updateTurnLabel(Check.turn);
    }
    
    /**
     *
     * @param gameName entered name of the game
     * @param whiteName entered white player name
     * @param blackName entered black player name
     */
    public GameFrame(String gameName, String whiteName, String blackName) {
        initComponents();
        this.whitePlayerName = whiteName;
        this.blackPlayerName = blackName;
        gameNameLabel.setText(gameName);
        updateTurnLabel(0);

        gameOverPanel.setVisible(false);
        pawnPromotionPanel2.setPromotionSelectionListener(this);
        pawnPromotionPanel2.setVisible(false);
        
        boardPanel.setMoveListener((algebraic,ply,curBoard,curTurn) -> {
           SaveGameDB.saveMove(Check.gameName, ply, algebraic); 
           SaveGameDB.updateTurnAndBoard(Check.gameName, curTurn, BoardStateCodec.encode(curBoard));
         });
        //If Check.* already holds a board (new game flow), show it
        if(BoardPanel.board != null)
        {
            boardPanel.loadState(BoardPanel.board, Check.turn);
        }
    }

    public GameFrame(String gameName, String whiteName, String blackName, Piece[][] board, int turn) {
        this.boardPanel = new chessproject2.GUI.BoardPanel(board, turn);
        initComponents();
        this.whitePlayerName = whiteName;
        this.blackPlayerName = blackName;
        gameNameLabel.setText(gameName);
        updateTurnLabel(turn);
        gameOverPanel.setVisible(false);
        pawnPromotionPanel2.setPromotionSelectionListener(this);
        pawnPromotionPanel2.setVisible(false);

        boardPanel.setMoveListener((algebraic,ply,curBoard,curTurn) -> {
           String state = chessproject2.ChessDB.BoardStateCodec.encode(curBoard);
           SaveGameDB.updateTurnAndBoard(Check.gameName, curTurn, state);
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pawnPromotionPanel1 = new chessproject2.GUI.PawnPromotionPanel();
        boardPanel = new chessproject2.GUI.BoardPanel();
        gameOverPanel = new chessproject2.GUI.GameOverPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pawnPromotionPanel2 = new chessproject2.GUI.PawnPromotionPanel();
        turnLabel = new javax.swing.JLabel();
        gameNameLabel = new javax.swing.JLabel();
        javax.swing.JButton Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        pawnPromotionPanel2.setPreferredSize(new java.awt.Dimension(380, 200));

        jLayeredPane1.setLayer(pawnPromotionPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(pawnPromotionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(pawnPromotionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1156, 1156, 1156))
            .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boardPanelLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(gameOverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boardPanelLayout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(gameOverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(180, Short.MAX_VALUE)))
        );

        turnLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        turnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnLabel.setText("Black Turn");

        gameNameLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        gameNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameNameLabel.setText("Game Name");

        Back.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back)
                                .addGap(80, 80, 80)
                                .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        HomeFrame home = new HomeFrame();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    public void updateTurnLabel(int currentTurn) {
        String playerName;
        if (currentTurn % 2 == 0) {
            playerName = whitePlayerName != null && !whitePlayerName.isEmpty() ? whitePlayerName : "White";
            turnLabel.setText("Turn: " + playerName);
        } else {
            playerName = blackPlayerName != null && !blackPlayerName.isEmpty() ? blackPlayerName : "Black";
            turnLabel.setText("Turn: " + playerName);
        }
    }

    public void gameover(boolean whiteWin) {
        gameOverPanel.setVisible(true);
        Color backgorundColor = new Color(220, 220, 220, 180);
        gameOverPanel.setBackground(backgorundColor);
        if (whiteWin) {
            gameOverPanel.winMessage.setText("White Wins!!!");
        } else {
            gameOverPanel.winMessage.setText("Black Wins!!!");
        }
    }

    /**
     * Called by BoardPanel when a pawn reaches the final rank.
     */
    public void showPawnPromotion(boolean isWhite, int row, int col) {
        // 1. Store the coordinates of the pawn
        this.promotionRow = row;
        this.promotionCol = col;

        // 2. Set the unicode symbols to the correct color
        pawnPromotionPanel2.setColor(isWhite);

        // 3. Show the promotion panel with a semi-transparent background
        Color backgorundColor = new Color(220, 220, 220, 180);
        pawnPromotionPanel2.setBackground(backgorundColor);
        pawnPromotionPanel2.setVisible(true);

        // Force a repaint on the layered pane to make sure the background is drawn
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }

    @Override
    public void onPieceSelected(String pieceType) {
        // 1. Hide the promotion panel
        pawnPromotionPanel2.setVisible(false);

        // 2. Call the BoardPanel method to finalize the promotion
        if (promotionRow != -1 && promotionCol != -1) {
            // boardPanel is the field declared in GameFrame
            boardPanel.finalizePawnPromotion(promotionRow, promotionCol, pieceType);
            //Persist board after promotion
            SaveGameDB.updateTurnAndBoard(Check.gameName, BoardPanel.turn, BoardStateCodec.encode(boardPanelBoard()));
            SaveGameDB.saveMove(Check.gameName, BoardPanel.turn, "promote = " + pieceType);
        }

        // 3. Reset the stored coordinates for the next promotion
        promotionRow = -1;
        promotionCol = -1;

        // The BoardPanel.finalizePawnPromotion handles turn increment and repaint.
    }
    
    private chessproject2.Pieces.Piece[][] boardPanelBoard()
    {
        return BoardPanel.board;
    }
    
    public void setWins(boolean isWhite)
    {
        if(isWhite)
        {
            PlayerDB.updateWins(whitePlayerName);
            PlayerDB.updateLosses(blackPlayerName);
        } else {
             PlayerDB.updateWins(blackPlayerName);
            PlayerDB.updateLosses(whitePlayerName);
        }
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chessproject2.GUI.BoardPanel boardPanel;
    private javax.swing.JLabel gameNameLabel;
    private chessproject2.GUI.GameOverPanel gameOverPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private chessproject2.GUI.PawnPromotionPanel pawnPromotionPanel1;
    private chessproject2.GUI.PawnPromotionPanel pawnPromotionPanel2;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
