/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chessproject2.GUI;

import chessproject2.ChessDB.BoardStateCodec;
import chessproject2.ChessDB.SaveGameDB;
import chessproject2.Game;

/**
 *
 * @author RyanL
 */
public class GameFrame extends javax.swing.JFrame {

    private String whitePlayerName;
    private String blackPlayerName;

    public GameFrame()
    {
        this(Game.gameName, Game.whiteName, Game.blackName);
        boardPanel.loadState(Game.board, Game.turn);
        updateTurnLabel(Game.turn);
    }
    
    /**
     *
     * @param gameName entered name of the game
     * @param whiteName entered white player name
     * @param blackName entered black player name
     */
    public GameFrame(String gameName, String whiteName, String blackName) {
        initComponents();
        this.whitePlayerName = whiteName;
        this.blackPlayerName = blackName;
        gameNameLabel.setText(gameName);
        updateTurnLabel(0);
        
        boardPanel.setMoveListener((algebraic, ply, curBoard, curTurn) -> {
            SaveGameDB.saveMove(Game.gameName, ply, algebraic);
            SaveGameDB.updateTurnAndBoard(Game.gameName, curTurn, BoardStateCodec.encode(curBoard));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new chessproject2.GUI.BoardPanel();
        turnLabel = new javax.swing.JLabel();
        gameNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        turnLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        turnLabel.setText("Black Turn");

        gameNameLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        gameNameLabel.setText("Game Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateTurnLabel(int currentTurn) {

        String playerName;

        if (currentTurn % 2 == 0) {

            playerName = whitePlayerName != null && !whitePlayerName.isEmpty() ? whitePlayerName : "White";

            turnLabel.setText("Turn: " + playerName);

        } else {

            playerName = blackPlayerName != null && !blackPlayerName.isEmpty() ? blackPlayerName : "Black";

            turnLabel.setText("Turn: " + playerName);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chessproject2.GUI.BoardPanel boardPanel;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
