/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chessproject2.GUI;

/**
 *
 * @author RyanL
 */
public class GameOverPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameOverPanel
     */
    public GameOverPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 200, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        winMessage.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        winMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winMessage.setText("White Winns!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(winMessage)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(winMessage)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel winMessage;
    // End of variables declaration//GEN-END:variables
}
