/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chessproject2.GUI;

import chessproject2.ChessDB.ChessDatabase;
import chessproject2.ChessDB.ReadGameDB;
import chessproject2.ChessDB.SaveGameDB;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RyanL
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        homeLabel = new javax.swing.JLabel();
        viewInstructionsButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();
        gameLogButton = new javax.swing.JButton();
        playerStatsButton1 = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Play Saved file");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess game");
        setAutoRequestFocus(false);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        homeLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        homeLabel.setText("Chess Game Home");

        viewInstructionsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewInstructionsButton.setText("View instructions");
        viewInstructionsButton.setToolTipText("");
        viewInstructionsButton.setMaximumSize(new java.awt.Dimension(150, 27));
        viewInstructionsButton.setMinimumSize(new java.awt.Dimension(150, 27));
        viewInstructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInstructionsButtonActionPerformed(evt);
            }
        });

        loadGameButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadGameButton.setText("Play Saved file");
        loadGameButton.setToolTipText("");
        loadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButtonActionPerformed(evt);
            }
        });

        newGameButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newGameButton.setText("Start new Game");
        newGameButton.setToolTipText("");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        gameLogButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gameLogButton.setText("View Game Logs");
        gameLogButton.setToolTipText("");
        gameLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameLogButtonActionPerformed(evt);
            }
        });

        playerStatsButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        playerStatsButton1.setText("View Player Stats");
        playerStatsButton1.setToolTipText("");
        playerStatsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerStatsButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewInstructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerStatsButton1)
                            .addComponent(gameLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(homeLabel)
                .addGap(70, 70, 70)
                .addComponent(viewInstructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(loadGameButton)
                .addGap(20, 20, 20)
                .addComponent(newGameButton)
                .addGap(20, 20, 20)
                .addComponent(playerStatsButton1)
                .addGap(20, 20, 20)
                .addComponent(gameLogButton)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewInstructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInstructionsButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "How to Play.... (Update this later, found in HomeFrame.java under viewInstructionsButton)");
    }//GEN-LAST:event_viewInstructionsButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadGameButtonActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // Create and show the new game window
        NewGameFrame newGame = new NewGameFrame();
        newGame.setVisible(true);

        // Close the current home window
        this.dispose();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void gameLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameLogButtonActionPerformed
        // TODO add your handling code here:
        //Make this into a drop down selection box
    }//GEN-LAST:event_gameLogButtonActionPerformed

    private void loadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButtonActionPerformed
        // TODO add your handling code here:
        List<String> games = SaveGameDB.listGameNames();
        if(games.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No saved games found.");
            return;
        }
        String sel = (String) JOptionPane.showInputDialog(
        this, "Select a saved game: ", "Load Game",
         JOptionPane.PLAIN_MESSAGE, null, games.toArray(), games.get(0)
        );
        if(sel == null) return;
        
        boolean ok = ReadGameDB.loadGame(sel);
        if(!ok)
        {
            JOptionPane.showMessageDialog(this, "Failed to load: " + sel);
            return;
        }
        
        //This assumes your GameFrame reads for static Game.* or has a default ctor.
        //If your GameFrame expects a BoardPanel/params, we'll wire it once you share GameFrame.java
        GameFrame gf = new GameFrame();
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loadGameButtonActionPerformed

    private void playerStatsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerStatsButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Coming soon: Player stats UI");
    }//GEN-LAST:event_playerStatsButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        ChessDatabase.init();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameLogButton;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton playerStatsButton1;
    private javax.swing.JButton viewInstructionsButton;
    // End of variables declaration//GEN-END:variables
}
