/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chessproject2.GUI;

import chessproject2.ChessDB.ChessDatabase;
import chessproject2.ChessDB.ReadGameDB;
import chessproject2.ChessDB.SaveGameDB;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author RyanL
 */
public class LoadGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoadGameFrame
     */
    public LoadGameFrame() {
        initComponents();
        setTitle("Load Game");
        setLocationRelativeTo(null);
        populateGameList();
        //load in combo box of all the loaded games
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderLabel = new javax.swing.JLabel();
        saveGameLabel = new javax.swing.JLabel();
        saveGameComboBox = new javax.swing.JComboBox<>();
        whiteNameDescription = new javax.swing.JLabel();
        blackNameDescription = new javax.swing.JLabel();
        whiteNameValueLabel = new javax.swing.JLabel();
        blackNameValueLabel = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        HeaderLabel.setText("Load Save File");

        saveGameLabel.setText("saved game name");

        saveGameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameComboBoxActionPerformed(evt);
            }
        });

        whiteNameDescription.setText("Loaded White Player Name:");

        blackNameDescription.setText("Loaded Black Player Name:");

        whiteNameValueLabel.setText("White name");

        blackNameValueLabel.setText("black name");

        loadButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(HeaderLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(saveGameLabel)
                        .addGap(70, 70, 70)
                        .addComponent(saveGameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(blackNameDescription)
                            .addComponent(whiteNameDescription)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(whiteNameValueLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(blackNameValueLabel)))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadButton)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(HeaderLabel)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveGameLabel)
                    .addComponent(saveGameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(whiteNameDescription)
                .addGap(44, 44, 44)
                .addComponent(whiteNameValueLabel)
                .addGap(42, 42, 42)
                .addComponent(blackNameDescription)
                .addGap(38, 38, 38)
                .addComponent(blackNameValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(backButton))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateGameList()
    {
        List<String> games = SaveGameDB.listGameNames();
        saveGameComboBox.removeAllItems();
       for (String g : games) saveGameComboBox.addItem(g);
       if(!games.isEmpty())
       {
           saveGameComboBox.setSelectedIndex(0);
           updateMetaLabels(games.get(0));
       } else {
            whiteNameValueLabel.setText("-");
            blackNameValueLabel.setText("-");
       }
    }
    
    private void updateMetaLabels(String gameName)
    {
        ReadGameDB.GameMeta meta = ReadGameDB.fetchGameMeta(gameName);
        if(meta == null)
        {
            whiteNameValueLabel.setText("-");
            blackNameValueLabel.setText("-");
        } else {
            whiteNameValueLabel.setText(meta.white);
            blackNameValueLabel.setText(meta.black);
        }
    }
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        HomeFrame home = new HomeFrame();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        String sel = (String) saveGameComboBox.getSelectedItem();
        if (sel == null) return;
        boolean ok = ReadGameDB.loadGame(sel);
        if(!ok)
        {
            JOptionPane.showMessageDialog(this, "Failed to load: " + sel);
            return;
        }
        GameFrame gf = new GameFrame();
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveGameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameComboBoxActionPerformed
            String sel = (String) saveGameComboBox.getSelectedItem();
            if (sel != null) updateMetaLabels(sel);
    }//GEN-LAST:event_saveGameComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel blackNameDescription;
    private javax.swing.JLabel blackNameValueLabel;
    private javax.swing.JButton loadButton;
    private javax.swing.JComboBox<String> saveGameComboBox;
    private javax.swing.JLabel saveGameLabel;
    private javax.swing.JLabel whiteNameDescription;
    private javax.swing.JLabel whiteNameValueLabel;
    // End of variables declaration//GEN-END:variables
}
