/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chessproject2.GUI;

import chessproject2.BoardFileIO;
import chessproject2.BoardStateUtil;
import chessproject2.ChessDB.BoardStateCodec;
import chessproject2.Player;
import chessproject2.ChessDB.PlayerDB;
import chessproject2.ChessDB.SaveGameDB;
import chessproject2.Check;
import java.util.HashMap;

/**
 *
 * @author RyanL
 */
public class NewGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewGameFrame() {
        initComponents();

        TextPrompt.addPlaceholder(gameNameField, "Enter game name");
        TextPrompt.addPlaceholder(wTextField, "Enter name here");
        TextPrompt.addPlaceholder(bTextField, "Enter name here");

        //Loads existing players from PlayerFileIO
        HashMap<String, Player> players = PlayerDB.loadPlayers();
        if (players != null && !players.isEmpty()) {
            boolean first = true;

            for (Player p : players.values()) {
                wExistingDropdown.addItem(p.getName());
                bExistingDropdown.addItem(p.getName());
                if (first) {
                    wExistingDropdown.setSelectedItem(p.getName());
                    bExistingDropdown.setSelectedItem(p.getName());
                    first = false;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wButtonGroup = new javax.swing.ButtonGroup();
        bButtonGroup = new javax.swing.ButtonGroup();
        header = new javax.swing.JLabel();
        wPannel = new javax.swing.JPanel();
        existingPlayerWRadial = new javax.swing.JRadioButton();
        newPlayerWRadial = new javax.swing.JRadioButton();
        whitePlayerLabel = new javax.swing.JLabel();
        wTextField = new javax.swing.JTextField();
        wExistingDropdown = new javax.swing.JComboBox<>();
        bPannel = new javax.swing.JPanel();
        existingPlayerBRadial = new javax.swing.JRadioButton();
        newPlayerBRadial = new javax.swing.JRadioButton();
        blackPlayerLabel = new javax.swing.JLabel();
        bTextField = new javax.swing.JTextField();
        bExistingDropdown = new javax.swing.JComboBox<>();
        gameNamePannel = new javax.swing.JPanel();
        gameNameLabel = new javax.swing.JLabel();
        gameNameField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Game");
        setSize(new java.awt.Dimension(600, 600));

        header.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        header.setText("Chess Setup");

        wPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        wButtonGroup.add(existingPlayerWRadial);
        existingPlayerWRadial.setText("Chose Existing Player");

        wButtonGroup.add(newPlayerWRadial);
        newPlayerWRadial.setSelected(true);
        newPlayerWRadial.setText("Create new player");

        whitePlayerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        whitePlayerLabel.setText("Chose White player");

        wTextField.setText("enter name here");
        wTextField.setToolTipText("enter name here");
        wTextField.setMinimumSize(new java.awt.Dimension(101, 22));
        wTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wPannelLayout = new javax.swing.GroupLayout(wPannel);
        wPannel.setLayout(wPannelLayout);
        wPannelLayout.setHorizontalGroup(
            wPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wPannelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(wPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(wPannelLayout.createSequentialGroup()
                        .addComponent(existingPlayerWRadial, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wExistingDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(wPannelLayout.createSequentialGroup()
                        .addComponent(newPlayerWRadial, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wPannelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(whitePlayerLabel)))
                .addGap(0, 0, 0))
        );
        wPannelLayout.setVerticalGroup(
            wPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(whitePlayerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlayerWRadial)
                    .addComponent(wTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingPlayerWRadial)
                    .addComponent(wExistingDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        bPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bButtonGroup.add(existingPlayerBRadial);
        existingPlayerBRadial.setText("Chose Existing Player");

        bButtonGroup.add(newPlayerBRadial);
        newPlayerBRadial.setSelected(true);
        newPlayerBRadial.setText("Create new player");

        blackPlayerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        blackPlayerLabel.setText("Chose Black player");

        bTextField.setText("enter name here");
        bTextField.setToolTipText("enter name here");
        bTextField.setMinimumSize(new java.awt.Dimension(101, 22));
        bTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bPannelLayout = new javax.swing.GroupLayout(bPannel);
        bPannel.setLayout(bPannelLayout);
        bPannelLayout.setHorizontalGroup(
            bPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bPannelLayout.createSequentialGroup()
                .addGroup(bPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bPannelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(bPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bPannelLayout.createSequentialGroup()
                                .addComponent(existingPlayerBRadial, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bExistingDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bPannelLayout.createSequentialGroup()
                                .addComponent(newPlayerBRadial, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bPannelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(blackPlayerLabel)))
                .addGap(160, 160, 160))
        );
        bPannelLayout.setVerticalGroup(
            bPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blackPlayerLabel)
                .addGap(18, 18, 18)
                .addGroup(bPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlayerBRadial)
                    .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingPlayerBRadial)
                    .addComponent(bExistingDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        gameNamePannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gameNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gameNameLabel.setText("Chose Game Name");

        gameNameField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        gameNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gameNameField.setText("enter game name");
        gameNameField.setToolTipText("enter game name");
        gameNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameNamePannelLayout = new javax.swing.GroupLayout(gameNamePannel);
        gameNamePannel.setLayout(gameNamePannelLayout);
        gameNamePannelLayout.setHorizontalGroup(
            gameNamePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameNamePannelLayout.createSequentialGroup()
                .addGroup(gameNamePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameNamePannelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(gameNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameNamePannelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(gameNameLabel)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        gameNamePannelLayout.setVerticalGroup(
            gameNamePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameNamePannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameNameLabel)
                .addGap(12, 12, 12)
                .addComponent(gameNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(146, 146, 146)
                .addComponent(createButton)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(header))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bPannel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(wPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gameNamePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(header)
                .addGap(36, 36, 36)
                .addComponent(gameNamePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(wPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backButton))
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTextFieldActionPerformed

    private void bTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTextFieldActionPerformed

    private void gameNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameNameFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        HomeFrame home = new HomeFrame();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String gName = getGameName();
        String wName = getWName();
        String bName = getBName();

        // --- FIX 1: SAVE NEW PLAYERS ---
        // Load existing players from the database
        HashMap<String, Player> players = PlayerDB.loadPlayers();

        // If the white player is new, add them to the map
        if (!players.containsKey(wName)) {
            players.put(wName, new Player(wName));
        }
        // If the black player is new, add them to the map
        if (!players.containsKey(bName)) {
            players.put(bName, new Player(bName));
        }

        // Save the updated player map back to the database
        PlayerDB.savePlayers(players);
        // --- END FIX 1 ---

        //Initialize global game state for the new game
        Check.gameName = gName;
        Check.whiteName = wName;
        Check.blackName = bName;
        Check.turn = 0;

        // --- FIX 2: (See below) ---
        // Use the correct, non-broken method to create the board
        BoardPanel.board = BoardStateCodec.initialBoardArray();

        //Persist into DB so later Load Check uses ReadGameDB
        // --- FIX 3 & 4: (See below) ---
        // Use the correct encoder that saves all required data
        SaveGameDB.saveOrUpdateGame(gName, wName, bName, 0, BoardStateCodec.encode(BoardPanel.board));

        //Launch the Check UI
        GameFrame home = new GameFrame(gName, wName, bName);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private String getGameName() {
        if (gameNameField.getText() != null && !gameNameField.getText().equals("Enter game name")) {
            return gameNameField.getText();
        }
        return "unNamed Game";
    }

    private String getWName() {
        if (newPlayerWRadial.isSelected()) {

            if (wTextField.getText() == null || wTextField.getText().equals("Enter name here")) {
                return "Anonymous";
            }
            return wTextField.getText();
        } else {
            return (String) wExistingDropdown.getSelectedItem();
        }
    }

    private String getBName() {
        if (newPlayerBRadial.isSelected()) {
            if (bTextField.getText() == null || bTextField.getText().equals("Enter name here")) {
                return "Anonymous";
            }
            return bTextField.getText();
        } else {
            return (String) bExistingDropdown.getSelectedItem();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bButtonGroup;
    private javax.swing.JComboBox<String> bExistingDropdown;
    private javax.swing.JPanel bPannel;
    private javax.swing.JTextField bTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel blackPlayerLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JRadioButton existingPlayerBRadial;
    private javax.swing.JRadioButton existingPlayerWRadial;
    private javax.swing.JTextField gameNameField;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JPanel gameNamePannel;
    private javax.swing.JLabel header;
    private javax.swing.JRadioButton newPlayerBRadial;
    private javax.swing.JRadioButton newPlayerWRadial;
    private javax.swing.ButtonGroup wButtonGroup;
    private javax.swing.JComboBox<String> wExistingDropdown;
    private javax.swing.JPanel wPannel;
    private javax.swing.JTextField wTextField;
    private javax.swing.JLabel whitePlayerLabel;
    // End of variables declaration//GEN-END:variables
}
