package chessproject2.GUI;

import chessproject2.Pieces.Knight;
import chessproject2.Pieces.Bishop;
import chessproject2.Pieces.Rook;
import chessproject2.Pieces.Queen;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 * This just displays the PawnPromotion panel when a pawn reaches the opposing
 * colors side, it allows you to choose between 4 pieces to change into
 *
 * @author RyanL and Yaacoub
 */
public class PawnPromotionPanel extends javax.swing.JPanel {

// New interface for the callback
    public interface PromotionSelectionListener {

        void onPieceSelected(String pieceType);
    }

// Add field and setter method
    private PromotionSelectionListener listener;

    public void setPromotionSelectionListener(PromotionSelectionListener listener) {
        this.listener = listener;
    }

    private static final Color DEFAULT_COLOR = new Color(220, 220, 220, 0); // Semi-transparent background
    private static final Color HOVER_COLOR = new Color(230, 230, 230, 255);  // Fully opaque background on hover

    /**
     * Creates new form PawnPromotionPanel
     */
    public PawnPromotionPanel() {
        initComponents();
        setColor(true); // not needed but safer so that the buttons load proper pieces rather than text

        addHoverEffect(knightButton);
        addHoverEffect(bishopButton);
        addHoverEffect(rookButton);
        addHoverEffect(queenButton);

        knightButton.setBackground(DEFAULT_COLOR);
        bishopButton.setBackground(DEFAULT_COLOR);
        rookButton.setBackground(DEFAULT_COLOR);
        queenButton.setBackground(DEFAULT_COLOR);

    }

    public void setColor(boolean color) {
        knightButton.setText(Knight.getUnicode(color));
        bishopButton.setText(Bishop.getUnicode(color));
        rookButton.setText(Rook.getUnicode(color));
        queenButton.setText(Queen.getUnicode(color));
    }

    // Helper method to add the MouseListener logic to a single component (now a JLabel)
    private void addHoverEffect(final javax.swing.JLabel label) { // Changed JButton to JLabel
        label.setOpaque(true); // Must be true for setBackground to work on a JLabel

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evt) {
                label.setBackground(HOVER_COLOR);
                // No need for explicit repaint(), as labels generally handle this better.
            }

            @Override
            public void mouseExited(MouseEvent evt) {
                label.setBackground(DEFAULT_COLOR);
                label.repaint();

                // Repaint the direct parent (PawnPromotionPanel), forcing the onhover to remove
                label.getParent().revalidate();
                label.getParent().repaint();

                if (label.getParent().getParent() != null) {
                    label.getParent().getParent().repaint();
                }
            }

            @Override
            public void mouseClicked(MouseEvent evt) {
                if (listener != null) {
                    // Identify the selected piece type based on the source component
                    String pieceType = "";
                    if (evt.getSource() == queenButton) {
                        pieceType = "Queen";
                    } else if (evt.getSource() == rookButton) {
                        pieceType = "Rook";
                    } else if (evt.getSource() == bishopButton) {
                        pieceType = "Bishop";
                    } else if (evt.getSource() == knightButton) {
                        pieceType = "Knight";
                    }

                    listener.onPieceSelected(pieceType);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rookButton = new javax.swing.JLabel();
        queenButton = new javax.swing.JLabel();
        knightButton = new javax.swing.JLabel();
        bishopButton = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 200));

        rookButton.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        rookButton.setText("PC");

        queenButton.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        queenButton.setText("PC");

        knightButton.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        knightButton.setText("PC");

        bishopButton.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        bishopButton.setText("PC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(rookButton)
                .addGap(35, 35, 35)
                .addComponent(bishopButton)
                .addGap(35, 35, 35)
                .addComponent(knightButton)
                .addGap(35, 35, 35)
                .addComponent(queenButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rookButton)
                    .addComponent(bishopButton)
                    .addComponent(knightButton)
                    .addComponent(queenButton))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bishopButton;
    public javax.swing.JLabel knightButton;
    public javax.swing.JLabel queenButton;
    public javax.swing.JLabel rookButton;
    // End of variables declaration//GEN-END:variables
}
