package chessproject2.GUI;

import chessproject2.ChessDB.PlayerDB;
import chessproject2.Player;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * PlayerStatsFrame shows the user all the current players that have been made
 * and there win losses stats
 *
 * @author RyanL and Yaacoub
 */
public class PlayerStatsFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlayerStatsFrame
     */
    public PlayerStatsFrame() {
        initComponents();
        setTitle("Player Stats");
        setLocationRelativeTo(null);
        loadPlayersIntoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        statsLabel = new javax.swing.JLabel();
        bakcButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Wins", "Losses"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        statsLabel.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        statsLabel.setText("Player Stats");

        bakcButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        bakcButton.setText("Back");
        bakcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(statsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(bakcButton)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(statsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bakcButton)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadPlayersIntoTable() {
        Map<String, Player> map = PlayerDB.loadPlayers();
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Name", "Wins", "Losses"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        if (map == null || map.isEmpty()) {
            jTable1.setModel(model);
            JOptionPane.showMessageDialog(this, "No Players found.");
            return;
        }
        for (Player p : map.values()) {
            model.addRow(new Object[]{p.getName(), p.getWins(), p.getLosses()});
        }
        jTable1.setModel(model);
    }

    private void bakcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakcButtonActionPerformed
        HomeFrame home = new HomeFrame();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bakcButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakcButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel statsLabel;
    // End of variables declaration//GEN-END:variables
}
